apiVersion: v1
kind: Pod
metadata:
  name: registry
spec:
  hostNetwork: true
  containers:
    - name: registry
      image: docker.io/library/registry:2
      volumeMounts:
        - name: config
          mountPath: /etc/docker/registry/config.yml
        - name: storage
          mountPath: /var/lib/registry
  volumes:
    - name: config
      hostPath:
          path: /etc/registry.yaml
          type: File
    - name: storage
      emptyDir: {}
